version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: sudo apt update
      - run: sudo apt install -y build-essential libssl-dev libncurses5-dev
      - run: sudo apt install -y cmake
      - run: mkdir build
      - run: cd build && cmake ..
      - run: cmake --build build
      - persist_to_workspace:
          root: .
          paths:
            - ./build
      - run: ls -R
  test:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - attach_workspace:
          at: .
      - run: ls -R
      - run: npm i -D tap-junit
      - run: BDD_USE_TAP=1 ./build/tests | ./node_modules/tap-junit/bin/tap-junit --output results
      - store_test_results:
          path: results

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build

